sync with other project

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,6 +25,13 @@ jobs:
     name: "Build - Python ${{ matrix.python-version }} on ${{ matrix.os }}"
     runs-on: "${{ matrix.os }}"
 
+    # ref: https://github.com/mikepenz/action-junit-report/issues/23
+    # ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
+    # required for junit report
+    permissions:
+      contents: read
+      checks: write
+
     strategy:
       matrix:
         os:
@@ -52,11 +59,9 @@ jobs:
       - name: "Install dependencies"
         run: |
           python -m pip install --upgrade pip
-          python -m pip install flake8
-          # python -m pip install prospector[with_everything]
-          # python -m pip install prospector
-          python -m pip install prospector[with_bandit,with_mypy]
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          python -m pip install --upgrade flake8
+          python -m pip install --upgrade prospector[with_bandit,with_mypy]
+          if [ -f requirements.txt ]; then python -m pip install --upgrade --requirement requirements.txt; fi
 
       - name: "List package versions"
         run: |
@@ -66,9 +71,9 @@ jobs:
         run: |
           # https://flake8.pycqa.org/en/latest/user/configuration.html
           # stop the build if there are Python syntax errors or undefined names
-          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .git,demo,docs,stock_db
+          python -m flake8 --select=E9,F63,F7,F82
+          # exit-zero treats all errors as warnings.
+          python -m flake8 . --exit-zero
 
       - name: "Lint with prospector"
         run: |
@@ -87,7 +92,16 @@ jobs:
       # https://docs.pytest.org/en/7.4.x/how-to/output.html
       - name: "Execute tests with coverage"
         run: |
-          python -m coverage run -a -m pytest -v -rfEsxXP --strict-markers
+          python -m coverage run -a -m pytest -v
+
+      - name: "Publish Test Report"
+        uses: mikepenz/action-junit-report@v4.0.3
+        if: success() || failure()  # always run even if the previous step fails
+        with:
+          summary: "pytest results"
+          report_paths: 'tests/results*.xml'
+          job_summary: true
+          detailed_summary: true
 
       # Append coverage (-a)
       - name: "Additional utilities execution"
